import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const gothamBook = localFont({
  src: "../public/fonts/GothamSSm-Book_Web.woff2",
  variable: "--font-gotham-book",
  weight: "100 900",
});
const gothamMedium = localFont({
  src: "../public/fonts/GothamSSm-Medium_Web.woff2",
  variable: "--font-gotham-medium",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Best Retirement Planner",
  description: "Generated by create next app",
  icons: {
    icon: "/public/favicon.ico",
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${gothamBook.variable} ${gothamMedium.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
